name: Build and Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12', '14', '16']

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3.1.0
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm

      - name: Update npm
        run: npm i -g npm

      - name: Install dependencies
        run: npm ci

      - name: Force package build
        run: npm run build

      - name: Run tests
        run: npm test
