name: Build and Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12', '14', '16']

    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1

      - name: Setup Node.js environment
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3.1.1
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm

      - name: Update npm
        run: npm i -g npm

      - name: Install dependencies
        run: npm ci

      - name: Force package build
        run: npm run build

      - name: Run tests
        run: npm test
